### ISSUE TITLE
Footer Re design

### ISSUE THREAD

**Issue by coletta1** [shenandoahliterary/Shenandoah#100]
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/44654153/73660357-0607bb80-4666-11ea-9e61-09296073bff4.png">

This is what my current reimplementation of the footer looks like. What do you think?

<img width="764" alt="image" src="https://user-images.githubusercontent.com/44654153/73660457-394a4a80-4666-11ea-85fa-b65dcad6611d.png">
Mockup for reference

**Comment by jeffreybarry** [comment]
Implemented Fall 2022
